version: "3.9"
services:
  db:
    image: postgres:latest # Use latest Postgres
    restart: always
    container_name: my-app-db-local
    ports:
      - "5432:5432" # Map default port
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
